### ISSUE TITLE
SKIA渲染韩文日文泰文等显示空白

### ISSUE THREAD

**Issue by xiaosongmao123** [soui3/soui#23]
你好，在使用SOUI3，但发现使用SKIA渲染时，text控件韩文，泰文等都显示为空白，不能正常显示
。

如果是韩语英语混杂（例如[cogito]신야재애린 2）时，显示为（[cogito]      2）并且cogito显示为宋体（设置显示字体为微软雅黑），应该是遇到韩文无法正常解析，并且将字体设置都丢了，只能强制显示为默认字体--宋体。

只要将渲染改为GDI，就没有这个问题了。不知是哪里的问题？？日文是可以正常显示的

感谢您的回答

**Comment by setoutsoft** [comment]
换字体，设置字体的charset属性等。
GDI可以渲染韩文是因为GDI有字体fallback，skia字体是自己做的，没有实现fallback。
3.0有fallback接口，不过需要自己去实现。
fallback就是一个字体里发现没有待输出的字符，就换一个有这个字符的字体。

**Comment by xiaosongmao123** [comment]
非常感谢 
这是我默认的
`<font face="微软雅黑" size="18"/>`

所以应该采用多个字体，并设置charset
`<font face="微软雅黑" size="18" charset=“134”/>`
`<font face="돋움" size="18" charset=“111”/>`

这样就可以了是吗？？我这就去测试一下

**Comment by xiaosongmao123** [comment]
`  <font face="微软雅黑" size="18" charset="134"/>`
 ` <font face="微软雅黑" size="18" charset="136"/>`
 ` <font face="굴림" size="18"  charset="129"/>`


我已经在init.xml这样设置了，但是仍然是显示空白，那么我还应该修改哪里，才能让text()正常显示中韩英混合的文字呢？？

`<text  font="size:18" >18_迭代器模式_신야재애린 2--测试文字</text>`

你看就是这样的一个text,显示不出来。。。。万分改写您的帮助

**Comment by xiaosongmao123** [comment]
还是说我必须向您提到的自己去实现一遍fallback接口（我用的soui3）,才行？？

**Comment by xiaosongmao123** [comment]
`<text font="face:굴림" >영웅, 회귀하다 04.zip</text>`  可以显示韩文和数字字母
`<text font="face:굴림" >영웅, 회귀하다 04.zip中文附加测试</text>`  只显示中文和数字字母

这又是为什么，，，，我再去看看fallback

**Comment by setoutsoft** [comment]
init.xml只能指定一种字体。不支持指定多个字体。

**Comment by setoutsoft** [comment]
我查了一下skia的代码，skia代码里创建字体的时候charset属性没有工作，不知道是不是skia版本太低的原因。有时间了我再研究一下怎么处理。

**Comment by xiaosongmao123** [comment]
嗯，老大真厉害。。。。。项目敢时间，我先放弃了，转回gdi了

**Comment by setoutsoft** [comment]
今天的版本已经修复了这个问题，只需要在font里指定charset:130这个属性就可以正常显示韩文了。
