### ISSUE TITLE
soui3 demo中界面无响应

### ISSUE THREAD

**Issue by vvsnow** [soui3/soui#27]
在下图红框区域, 当鼠标左键按下并拖动一下, 然后整个界面就卡在哪里不能操作了

![image](https://user-images.githubusercontent.com/12657196/89088755-86686880-d3cc-11ea-99f8-bfb88f0b04d6.png)

**Comment by setoutsoft** [comment]
一个网友提供的扩展控件，可能没有处理这些操作。
