### ISSUE TITLE
SQrCtrl控件，在二维码绘制过程中，镜像翻转了 

### ISSUE THREAD

**Issue by w1146869587** [soui3/soui#29]
SQrCtrl控件，在二维码绘制过程中，镜像翻转了，导致在pda设备中，扫码无法识别。建议在创建CreateBitmap时，修改如下代码：
int qrSize = qrEncode.m_nSymbleSize + (QR_MARGIN * 2);
			CAutoRefPtr<IBitmap> bmp;
			GETRENDERFACTORY->CreateBitmap(&bmp);
			bmp->Init(qrSize, qrSize);
			LPDWORD pBits = (LPDWORD)bmp->LockPixelBits();
			memset(pBits, 0xFF, qrSize*qrSize * 4);
			int nLineWid = qrSize;
			LPDWORD pLine = pBits + QR_MARGIN*nLineWid;
			for (int i = 0; i < qrEncode.m_nSymbleSize; ++i)
			{
				LPDWORD pLineData = pLine + QR_MARGIN;
				for (int j = 0; j < qrEncode.m_nSymbleSize; ++j)
				{
					if (qrEncode.m_byModuleData[j][i])
					{
						pLineData[j] = RGBA(0, 0, 0, 255);
					}
				}
				pLine += qrSize;
			}
			bmp->UnlockPixelBits(pBits);
			SetImage(bmp);

**Comment by setoutsoft** [comment]
不确定是什么情况，我在demo上用现在的代码生成的二维码，常用的扫描器都可以识别。如果确实有问题，自己改代码就好了。反正只是一个扩展控件。
